sed -i 's#/process#/services/search/process#g' archaea.ejs
sed -i 's#/process#/services/search/process#g' bacteria.ejs
sed -i 's#/process#/services/search/process#g' bindingsite.ejs
sed -i 's#/process#/services/search/process#g' details.ejs
sed -i 's#/process#/services/search/process#g' eukaryota.ejs
sed -i 's#/process#/services/search/process#g' gene.ejs
sed -i 's#/process#/services/search/process#g' genes.ejs
sed -i 's#/process#/services/search/process#g' genesSearch.ejs
sed -i 's#/process#/services/search/process#g' genomes.ejs
sed -i 's#/process#/services/search/process#g' genomesSearch.ejs
sed -i 's#/process#/services/search/process#g' home2.ejs
sed -i 's#/process#/services/search/process#g' index.ejs
sed -i 's#/process#/services/search/process#g' layout.ejs
sed -i 's#/process#/services/search/process#g' literature.ejs
sed -i 's#/process#/services/search/process#g' literatureSearch.ejs
sed -i 's#/process#/services/search/process#g' locus.ejs
sed -i 's#/process#/services/search/process#g' mrna.ejs
sed -i 's#/process#/services/search/process#g' operator.ejs
sed -i 's#/process#/services/search/process#g' process.ejs
sed -i 's#/process#/services/search/process#g' processError.ejs
sed -i 's#/process#/services/search/process#g' promoter.ejs
sed -i 's#/process#/services/search/process#g' prophage.ejs
sed -i 's#/process#/services/search/process#g' proteinbindingsite.ejs
sed -i 's#/process#/services/search/process#g' pseudogene.ejs
sed -i 's#/process#/services/search/process#g' riboswitch.ejs
sed -i 's#/process#/services/search/process#g' rna.ejs
sed -i 's#/process#/services/search/process#g' rnaSearch.ejs
sed -i 's#/process#/services/search/process#g' smallrna.ejs
sed -i 's#/process#/services/search/process#g' testCount.ejs
sed -i 's#/process#/services/search/process#g' test.ejs
sed -i 's#/process#/services/search/process#g' transposon.ejs
sed -i 's#/process#/services/search/process#g' viruses.ejs
